# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8615a4dbf13ac1f49c7ad77a7233f5f67f3f2ee102068e651115db54584821c415ce66dbf8367bd8f64480e301561ef526166bd731ab57a5c9a2aab17802c74f

test:
  secret_key_base: 24a0ce783e2362d69e26495858fa8ba28e6fbbd498d8bdff1d23449cb407167831016e5d4a6ae4a7bb9bbd5e7d82ede1983486000652d173a38fb50f5857d590

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
